id: ACE2BC434
title: Clouds of Offerings to Delight the Victorious Ones – An Aspiration Prayer for
  the Spread of the Teachings of the Lord of Siddhas, Dzogchen Rinpoche
type: translation
pechas:
- IC2C8EA12
- I1949D95E
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:55:15.124896
  last_modified_at: 2023-01-04 12:55:15.124922
  collections:
  - Khenpo Tsöndrü Series
  - Works of Tibetan Masters
alignment_to_base:
  IC2C8EA12/CC24: '3106'
  I1949D95E/B7C6: '3106'
